import Head from 'next/head'
import { Features } from '../src/components/features/Features'
import { Header } from '../src/components/header/Header'
import { Hero } from '../src/components/hero/Hero'
import { Pricing } from '../src/components/pricing/Pricing'
import { Testimonials } from '../src/components/testimonials/Testimonials'

export default function Home() {
  return (
    <div>
      <Head>
        <title>LightyearKids</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/lk-logo.png" />
      </Head>

      <main>
        <Header />
        <Hero />
        <Features />
        <Testimonials />
        <Pricing />
      </main>

      <footer>
        Footer
      </footer>
    </div>
  )
}
