import Head from 'next/head'
import { Header } from '../src/components/header/Header'
import { Hero } from '../src/components/hero/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>LightyearKids</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/lk-logo.png" />
      </Head>

      <main>
        <Header />
        <Hero />
      </main>

      <footer>
        Footer
      </footer>
    </div>
  )
}
